Repository EMBL-EBI-ABC/PerturbationCatalogue, pull requests merged in 2025-04, with the labels that each got.

#158 Migrate to Dash 3
  fe/app.py
  fe/requirements.txt
Labels: Component: FE, Type: Enhancement

#161 Streamline deployment instructions & fix main page live deployment bug
  be/README.md
  fe/README.md
Labels: Type: Enhancement, Component: Docs

#166 Refactor `ElasticTable` store and callback structure
  fe/pages/data_portal.py
  fe/pages/elastic_table.py
Labels: Component: FE, Type: Refactor

#167 Initialise table layout from central state if provided
  fe/pages/elastic_table.py
Labels: Component: FE, Type: Feature

#168 Persist state of `ElasticTable` using URL
  fe/app.py
  fe/pages/data_portal.py
Labels: Component: FE, Type: Feature

#172 Adjusted metadata schema
  data_exploration/unified_metadata_schema/unified_metadata_schema.py
  unified_metadata_schema.json
Labels: Component: Data, Type: Enhancement
